version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=ddd-example
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - '3306:3306'
    networks:
      - ddd-example-network
  backend:
    restart: unless-stopped
    depends_on:
      - db
    build: ./
    ports:
      - "8080:8080"
    networks:
      - ddd-example-network
volumes:
  db:
networks:
  ddd-example-network:
