version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=ddd-example
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - '3306:3306'
  db-test:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=ddd-example-test
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - '3307:3306'
